### ISSUE TITLE
node-sp-auth-config fails to start (sp-auth --help)

### ISSUE THREAD

**Issue by gregd72002** [koltyakov/node-sp-auth-config#12]
I am getting error when running sp-auth:

On a fresh system:
npm --version
3.5.2

nodejs --version
v4.2.6

npm install node-sp-auth-config -g
[ALL GETS INSTALLED FINE]

sp-auth --help 
/usr/local/lib/node_modules/node-sp-auth-config/dist/cli.js:8
const { version } = require(path.join(__dirname, '..', 'package.json'));
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by koltyakov** [comment]
Hey Greg,

Just wondering, is there any reason using such an old Node.js version?

**Comment by gregd72002** [comment]
this is the stable version release with Ubuntu 16.04 LTS. Which is the most current LTS Ubuntu version.

**Comment by koltyakov** [comment]
Nope. Node.js ver. 8 is current LTS. 4th is way too ooooold 👴
Please check how to install an up-to-date [Node on Ubuntu](http://nodesource.com/blog/installing-node-js-8-tutorial-linux-via-package-manager/).
