### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by himyulian** [koltyakov/node-sp-auth-config#20]
I get this error while building the application:

**warning  
in ./node_modules/node-sp-auth-config/dist/index.js
Critical dependency: the request of a dependency is an expression**

At the same time, when launching the application in the console there is such an error:
**Error: No such module. (Possibly not yet loaded)**

Please help solve the problem

My package.json:

{
  "name": "test",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@pnp/common": "^1.2.9",
    "@pnp/graph": "^1.2.9",
    "@pnp/logging": "^1.2.9",
    "@pnp/nodejs": "^1.3.0",
    "@pnp/odata": "^1.2.9",
    "@pnp/sp": "^1.2.9",
    "babel-polyfill": "^6.26.0",
    "leaflet": "^1.4.0",
    "leaflet-ajax": "^2.1.0",
    "node-pnp-js": "^0.1.3",
    "pnp-auth": "^0.0.4",
    "readline": "^1.3.0",
    "register-service-worker": "^1.5.2",
    "vue": "^2.6.6",
    "vue-class-component": "^6.0.0",
    "vue-property-decorator": "^7.0.0",
    "vue-router": "^3.0.1",
    "vuetify": "^1.5.5",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@babel/preset-env": "^7.3.4",
    "@vue/cli-plugin-babel": "^3.4.0",
    "@vue/cli-plugin-eslint": "^3.4.0",
    "@vue/cli-plugin-pwa": "^3.4.0",
    "@vue/cli-plugin-typescript": "^3.4.0",
    "@vue/cli-service": "^3.4.0",
    "@vue/eslint-config-standard": "^4.0.0",
    "@vue/eslint-config-typescript": "^4.0.0",
    "babel-eslint": "^10.0.1",
    "eslint": "^5.8.0",
    "eslint-plugin-vue": "^5.0.0",
    "node-sass": "^4.9.0",
    "sass-loader": "^7.1.0",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.1",
    "typescript": "~3.2.2",
    "vue-cli-plugin-vuetify": "^0.5.0",
    "vue-template-compiler": "^2.5.21",
    "vuetify-loader": "^1.0.5"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "@vue/standard",
      "@vue/typescript"
    ],
    "rules": {},
    "parserOptions": {
      "parser": "@typescript-eslint/parser"
    }
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}

**Comment by koltyakov** [comment]
Looks like something wrong locally on the machine or even more likely it's something related to Webpack.

Did you try removing node_modules and package-lock.json and installing reinstalling the dependencies?

Also, you're loading `node-pnp-js` and `pnp-auth` which do the same thing, yet `pnp-auth` is a successor library.

![image](https://user-images.githubusercontent.com/7816483/54352907-bdb56880-4663-11e9-9405-9bfc6081923c.png)

Also, I hope that you aren't intending bundling `node-sp-auth` as a code for a browser as it can only be used in Node.js.

**Comment by himyulian** [comment]
Andrew, unfortunately your recommendations did not correct the situation.
I deleted node_modules and package-lock.json and reinstalled the dependencies.
I also removed the node-pnp-js from dependencies.

my project created using vue/cli3.0
There is nothing but default installation and an bootstrap example.

if you do not mind, please see the source. 
https://send.firefox.com/download/54d81db072/#rUQIweoA2sZAEl9r2m_Qvg

I would be very grateful if you can help me figure out why this error still occurs when compiling the project.
