### ISSUE TITLE
cli hangs at "Authentication strategy (Use arrow keys)"

### ISSUE THREAD

**Issue by jgranduel** [koltyakov/node-sp-auth-config#21]
Hi, 

I've installed node-sp-auth-config locally, then globally.
I want to generate config for SharePoint On Premise 2013. It always hangs at second step.

I tried different node versions (v12.4.0 and v11.10.0), with npx locally or with np-auth CLI.
Same result. I cannot do anything but kill the process at second step.

sp-auth  init  -p ./ntlm.json
```
Win10/PowerShell> sp-auth  init  -p ./ntlm.json

? SharePoint URL https://sites.x.y/path/to/mysite
? Authentication strategy (Use arrow keys)
> User credentials (NTLM)  <-- cannot move, not even do anything!
```
please, check the strategy  is handled.
Thanks in advance!

**Comment by koltyakov** [comment]
Thanks for reporting this. Yes, looks like an issue. Works as expected in a library mode. But CLI stuck on strategy selection. Investigating it now...

**Comment by koltyakov** [comment]
Published the hotfix. Can you please check v2.6.6?
The issue seems to be caused by one of the dependencies, which is in charge of UI std* interactions. Connected issue https://github.com/SBoudrias/Inquirer.js/issues/811

**Comment by jgranduel** [comment]
Hi, 

I can confirm it actually worked out fine. You've been so fast that I thought I had forgotten to really post!
Many thanks!
