### ISSUE TITLE
specify siteUrl and strategy in code

### ISSUE THREAD

**Issue by jmls** [koltyakov/node-sp-auth-config#29]
so, if I use the cli, a wizard asks for the strategy and siteUrl

what if I want to create the authConfig in code ?  I can create a new AuthConfig, and specify the domain, user and password .. but not the siteUrl or strategy (both of which go into the config.json file)

**Comment by koltyakov** [comment]
Can you elaborate? Sorry, didn’t get the question. 
You can completely disable any prompts. Use defaults if you need something predefined. Overwrite any props before passing to API client. Use environment variables, etc.
If the intention is using same creds, but multiple destinations (sites within the same farm, for instance), after resolving a config you can provide siteUrl in a custom manner before passing creds further to auth factory.

**Comment by jmls** [comment]
sorry, I'll try and explain better ;)

I need to allow the users to configure system via a rest call - so I can't prompt from the cli.  I need to set the siteUrl and strategy so that it is stored in the config.json that gets created when you invoke .getContext()

at the moment, I get this in the config :

```
{
  "siteUrl": "",
  "username": "<user>",
  "password":  "<pass>,
  "domain": "foo"
}
```

whereas if I create the authconfig via the cli it is

```
{
    "siteUrl": "http://myurl/sites/customer",
    "strategy": "OnpremiseUserCredentials",
    "username": "<user>",
    "domain": "foo",
    "password": "<pass>!"
}

```

I'm trying to get the siteUrl and strategy to be saved when the other properties are saved

**Comment by koltyakov** [comment]
So you do a standalone solution that should have a user login form and then take data out of SharePoint in a user context? It's always not a good idea, as you would ask for credentials in the external site when accessing SharePoint or end up storing user credentials. I can't encourage such a design in general. It would be more correct to place the SPA assets/page into SharePoint, consuming user contextual data via client-side APIs, run elevated request server-side exposing methods via web services.

I know little about why you need getting creds via a REST Call, just warning you it might be a sign that something is wrong. If to abstract from everything, and imagine that creds must be received via a service call and used then no need in node-sp-auth-config, but pass creds directly to node-sp-auth or what's in the middle.

For a service like this, node-sp-auth-config's prompts must be disabled, you don't want a service stuck with a console prompt, headless mode is enabled automatically with `process.env.NODE_ENV="production"` (https://github.com/koltyakov/node-sp-auth-config#production-runtime).

I'd spotlight the major use cases for the library:
- Use in CLI and local toolchains
- Service account configuration in runtime environments (cases, when different creds management system such as Vault are overkill)

**Comment by koltyakov** [comment]
Going to close this. Please reopen if you still have questions.
