### ISSUE TITLE
What about cli? :)

### ISSUE THREAD

**Issue by s-KaiNet** [koltyakov/node-sp-auth-config#5]
I can work on it :)

**Comment by koltyakov** [comment]
Good idea and relatively easy to implement.
Any ideas about CLI's API (set of parameters and actions)?

> I can work on it :)

It would be great if you have some time.

**Comment by s-KaiNet** [comment]
I'm thinking about `configPath` and `encryptPassword` params. `saveConfigOnDisk` will be always true.   
[`commander`](https://github.com/tj/commander.js) for input handling.

**Comment by koltyakov** [comment]
Oh, btw. I almost the same for SPAuthN some time ago. With [stringToArgvs](https://github.com/koltyakov/SPAuthN/blob/master/SPAuthN/auth/utils/index.js#L5) and ) and:
```javascript
let authOptions = Object.assign({}, {
  configPath: './config/private.json',
  encryptPassword: true,
  saveConfigOnDisk: true
}, utils.stringToArgvs(args));
```
All `IAuthConfigSettings` were passed including child properties, like `authOptions.password`.
In SPAuthN such params work: 
```
--authOptions.siteUrl="http://sharepoint" --authOptions.username="user@contoso.com" --authOptions.password="p@ssw0rd" --saveConfigOnDisk=false
```
I'm wondering, what should be the expected result of a CLI command (node-sp-auth response, message about successful connection and created json with credentials)?

**Comment by koltyakov** [comment]
Yet, as a CLI tool, it's better embracing `program` module which we used in sp-download and sphooks cause it generates help output, which is super important in CLI tools.

**Comment by s-KaiNet** [comment]
From my POV cli just creates a file by utilizing full power of enquirer module. So cli doesn't expect username or password as an input, that's a work for node-sp-auth-config to ask for a creds, however cli helps generating the file anywhere.   
> Yet, as a CLI tool, it's better embracing program module which we used in sp-download and sphooks cause it generates help output, which is super important in CLI tools.   

sp-download uses commander. Don't you confuse with something else?

**Comment by koltyakov** [comment]
> So cli doesn't expect username or password as an input

Yeah. You're absolutely right.

sp-download uses [program](https://github.com/koltyakov/sp-download/blob/master/src/cli.ts#L12).

> Don't you confuse with something else?

Maybe I was thinking about [spfx-extensions-cli](https://github.com/vman/spfx-extensions-cli/blob/master/src/index.ts#L18).

Anyway, when I tryed `program` I liked it. Was very neat to get free help output. =)

**Comment by s-KaiNet** [comment]
It [uses](https://github.com/koltyakov/sp-download/blob/master/src/cli.ts#L4) [commander](https://github.com/koltyakov/sp-download/blob/master/package.json#L35) however you can give it any name during import :)

**Comment by koltyakov** [comment]
Oh, shoot! You're right. Sorry! Maybe I need some days off. ;)

**Comment by s-KaiNet** [comment]
Hopefully October Revolution holiday will be soon 😄

**Comment by koltyakov** [comment]
LOL! Now they call it "Unity Day". Have no idea the unity of whom with whom. But maybe it's time to learn game engine.

**Comment by s-KaiNet** [comment]
WOW, we're still celebrating old fashioned October Revolution. As your government renamed it to "Unity Day", then we need to propose to our something like "Blockchain Day" (to stay in line with modern world) 😊
